// Shared tooltip definitions for the Rent vs Own calculator.
// Used by both rentvsownhouse/index.html and rentvsownhouse/sensitivity/index.html.
var RVO_TIPS = {
  propertyPrice:        "The current market purchase price of the property being modelled. This is the starting value for house equity and mortgage calculations.",
  downPaymentPct:       "The percentage of the property price paid upfront as a deposit. Set to 100% to model an all-cash purchase (no mortgage). Try different values; 20% isn't always optimal. The renter equivalent invests this same amount instead.",
  mortgageType:         "<strong>Principal &amp; Interest:</strong> each payment reduces both interest and loan balance, building equity faster.<br><strong>Interest Only:</strong> payments cover only interest; principal stays unchanged until term ends. Lower monthly payments but no equity built from repayments.",
  costInterestOnly:     "<strong>ON:</strong> Accumulated Cost counts only interest + ongoing (money truly lost; principal repayment builds equity).<br><strong>OFF:</strong> Full mortgage payment + ongoing are treated as outgoing costs.",
  mortgageRate:         "The annual interest rate charged on the mortgage. This determines the monthly repayment amount.<br><strong>P&amp;I:</strong> higher rates mean more interest and slower equity build.<br><strong>IO:</strong> rate directly sets the monthly payment.",
  mortgageTerm:         "The total number of years over which the loan is amortised. A longer term means lower monthly payments but more total interest paid. Once the loan is fully repaid, the entire monthly budget becomes surplus savings.",
  houseGrowth:          "The Residential Property Price Index annual growth rate: how much the property appreciates each year. This drives house equity growth and the future purchase price in the Rent-Then-Buy scenario. Use the CAGR calculator below to derive this from historical data.",
  setupCost:            "One-time upfront costs when purchasing the property — includes stamp duty, conveyancing, building inspection, and other transaction fees. Paid from savings (not added to the loan) and reduces the renter's initial investable capital.",
  ownOngoingCost:       "Annual recurring costs of owning the property beyond the mortgage: council rates, building insurance, maintenance, strata levies, land tax, lawn care, etc. Can be entered as a fixed dollar amount or as a % of current property value.",
  ownOngoingInflation:  "Annual rate at which fixed-dollar ongoing ownership costs increase. Applies only when 'Fixed $ amount' is selected; % of property value already grows with house appreciation.",
  rentAmount:           "The current weekly, monthly, or yearly rent payment. This is the base figure that grows each year at the Rent Inflation rate. The renter invests any monthly budget surplus above this rent amount.",
  rentInflation:        "The annual rate at which rent increases each year. Historical rent inflation has typically tracked general CPI or slightly above. Higher rent inflation erodes the renter's monthly surplus faster over time.",
  rentOngoingCost:      "Extra costs the renter bears beyond the base rent: contents insurance, renters' insurance, utility connection fees, etc. Unlike owners, renters don't pay council rates or building maintenance — so this is typically much lower than the own scenario.",
  rentOngoingInflation: "Annual rate at which fixed-dollar renting ongoing costs increase. Applies only when 'Fixed $ amount' is selected; % of annual rent already grows with rent inflation.",
  riskFreeRate:         "The annual return earned on any uninvested cash: surplus above rent or mortgage, and any leftover initial cash. Could be a HYSA, term deposit, ETFs, or bonds. Both scenarios compound idle cash at this rate.",
  initialCash:          "Your total cash available right now. This funds the down payment + setup costs for the Buy scenario. Any leftover is invested at the risk-free rate from day one. The Rent scenario invests the full amount from day one. If left blank, it defaults to exactly down payment + setup cost (no surplus, no shortfall).",
  monthlyBudget:        "The total monthly cash available for housing costs. If left blank, it's auto-set to the higher of rent or mortgage payment each year. Any surplus above actual costs is invested at the risk-free rate.",
  monthlyBudgetIncrease:"The rate at which your monthly housing budget grows each year. Only applies when a manual budget is set above. Use this to model wage growth, CPI adjustments, or property-linked cost increases. The budget compounds at this rate annually, growing the surplus (or shrinking the shortfall) over time.",
  horizon:              "Number of years to project the scenario. Longer horizons allow property compounding and mortgage payoff effects to fully materialise. Up to 100 years supported.",
  rtbEnabled:           "Model a third scenario where you rent for X years, then buy the property at the then-current market price. This helps compare the optimal timing of entry into property ownership.",
};
